[font]
  normal = { family = "Fira Code" }
  bold = { family = "Fira Code" }
  italic = { family = "Fira Code" }
  bold_italic = { family = "Fira Code" } 
  size = 7

[cursor]
  style = "Block"
  blink_interval = 0

[scrolling]
  history = 2000

[window]
  opacity = 1

[selection]
  save_to_clipboard = true

[mouse] 
  hide_when_typing = true

[colors.primary]
    background = "#232136"
    foreground = "#e0def4"
 #   selection = { text = "#e0def4", background = '#44415a' }

# cursor = { text = "#e0def4", cursor = '#56526e' }

[colors.normal]
    black =   "#393552"
    red =     "#eb6f92"
    green =   "#3e8fb0"
    yellow =  "#f6c177"
    blue =    "#9ccfd8"
    magenta = "#c4a7e7"
    cyan =    "#ea9a97"
    white =   "#e0def4"

[colors.bright]
    black =   "#6e6a86"
    red =     "#eb6f92"
    green =   "#3e8fb0"
    yellow =  "#f6c177"
    blue =    "#9ccfd8"
    magenta = "#c4a7e7"
    cyan =    "#ea9a97"
    white =   "#e0def4"

[terminal.shell]
    program = "/usr/bin/tmux"
    args = [ "new-session", "-A", "-D", "-s", "main" ]

# Note = Keybindings, tabs, layouts, and window management features from Kitty are not supported directly in Alacritty.
# Use tmux or another terminal multiplexer for advanced layout functionality.
