
vim.keymap.set('n', '<leader>ne', function() vim.diagnostic.jump({count=1, float=true}) end)
vim.keymap.set('n', '<leader>pe', function() vim.diagnostic.jump({count=-1, float=true}) end)
vim.keymap.set('n', '<leader>1', '<cmd>tabn 1<CR>')
vim.keymap.set('n', '<leader>2', '<cmd>tabn 2<CR>')
vim.keymap.set('n', '<leader>3', '<cmd>tabn 3<CR>')
vim.keymap.set('n', '<leader>4', '<cmd>tabn 4<CR>')
vim.keymap.set('n', '<leader>5', '<cmd>tabn 5<CR>')
vim.keymap.set('n', '<leader>6', '<cmd>tabn 6<CR>')
vim.keymap.set('n', '<leader>7', '<cmd>tabn 7<CR>')
vim.keymap.set('n', '<leader>8', '<cmd>tabn 8<CR>')
vim.keymap.set('n', '<leader>9', '<cmd>tabn 9<CR>')
vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename)
vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action)
vim.keymap.set('n', '<leader>cf', function () vim.lsp.buf.format({ async = false }) end)
vim.keymap.set('n', '<leader>df', vim.lsp.buf.definition)
vim.keymap.set('n', 'K', vim.lsp.buf.hover)
vim.keymap.set('i', '<C-BS>', "<C-w>")
vim.keymap.set('i', '<C-H>', "<C-w>")
vim.keymap.set('i', '<C-k>', vim.lsp.buf.signature_help)

vim.keymap.set('n', 'fR', function() vim.lsp.buf.references() end)
vim.keymap.set('v', "J", ":m '>+1<CR>gv=gv")
vim.keymap.set('v', "K", ":m '<-2<CR>gv=gv")
