require('common')
hl.bind(MainMod .. " + F",                          hl.dsp.window.fullscreen())
hl.bind(MainMod .. " + P",			                hl.dsp.window.pseudo())
hl.bind(MainMod .. " + C",			                hl.dsp.window.close())
hl.bind(MainMod .. " + SPACE",		                hl.dsp.window.float({ action = "toggle" }) )
hl.bind(MainMod .. " + l",			                hl.dsp.focus({ direction = "right" }))
hl.bind(MainMod .. " + h",			                hl.dsp.focus({ direction = "left" }))
hl.bind(MainMod .. " + k",			                hl.dsp.focus({ direction = "up" }))
hl.bind(MainMod .. " + j",			                hl.dsp.focus({ direction = "down" }))
hl.bind(MainMod .. " + mouse:272",                  hl.dsp.window.drag(),   { mouse = true })
hl.bind(MainMod .. " + mouse:273",                  hl.dsp.window.resize(), { mouse = true })
hl.bind(MainMod .. " + S",                          hl.dsp.workspace.toggle_special("magic"))
hl.bind(MainMod .. " + SHIFT + S",                  hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(MainMod .. " +  TAB",                       hl.dsp.window.cycle_next({""}))
hl.bind(MainMod .. " + X", function ()
    if hl.get_workspace("special:minimized") then
        hl.dispatch(hl.dsp.window.move({ workspace = hl.get_active_workspace(), window = "tag:minimized" }))
        hl.dispatch(hl.dsp.window.clear_tags({ window = "tag:minimized" }))
    else
        hl.dispatch(hl.dsp.window.tag({ tag = "minimized", window = hl.get_active_window() }))
        hl.dispatch(hl.dsp.window.move({ workspace = "special:minimized", follow = false }))
    end
end)
hl.bind(MainMod .. " + S",  hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(MainMod .. " + C",	                hl.dsp.window.kill())
hl.bind(MainMod .. " + l",			                        hl.dsp.window.swap({ direction = "right" }))
hl.bind(MainMod .. " + h",			                        hl.dsp.window.swap({ direction = "left" }))
hl.bind(MainMod .. " + k",			                        hl.dsp.window.swap({ direction = "up" }))
hl.bind(MainMod .. " + j",			                        hl.dsp.window.swap({ direction = "down" }))

hl.bind(MainMod .. " + T",                     hl.dsp.exec_cmd("~/bin/alacritty.sh"))
hl.bind(MainMod .. " + E",			                hl.dsp.exec_cmd(FileManager))
hl.bind(MainMod .. " + B",			                hl.dsp.exec_cmd(Browser))
hl.bind(MainMod .. " + M",			                hl.dsp.exec_cmd("spotify-launcher"))
-- hl.bind(MainMod .. " + V",			                hl.dsp.exec_cmd("pavucontrol"))
hl.bind(MainMod .. " + E",			        hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(MainMod .. " + R",			                hl.dsp.exec_cmd(Menu))
hl.bind(MainMod .. " + F",                            hl.dsp.exec_cmd("~/bin/ranger.sh"))
