require('common')
hl.bind(Meh .. " + S",  hl.dsp.exec_cmd("hyprshot -m region"), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Meh .. " + C",	                hl.dsp.window.kill(), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Meh .. " + l",			                        hl.dsp.window.swap({ direction = "right" }), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Meh .. " + h",			                        hl.dsp.window.swap({ direction = "left" }), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Meh .. " + k",			                        hl.dsp.window.swap({ direction = "up" }), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Meh .. " + j",			                        hl.dsp.window.swap({ direction = "down" }), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})

hl.bind(Hyper .. " + T",                     hl.dsp.exec_cmd("~/bin/alacritty.sh"), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Hyper .. " + E",			                hl.dsp.exec_cmd(FileManager), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Hyper .. " + B",			                hl.dsp.exec_cmd(Browser), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Hyper .. " + M",			                hl.dsp.exec_cmd("spotify-launcher"), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Hyper .. " + V",			                hl.dsp.exec_cmd("pavucontrol"), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Hyper .. " + E",			        hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
-- hl.bind(Hyper .. " + R",			                hl.dsp.exec_cmd(Menu), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
hl.bind(Hyper .. " + F",                            hl.dsp.exec_cmd("~/bin/ranger.sh"), {device = {inclusive = true, list = {"zsa-technology-labs-moonlander-mark-i"}}})
