require('common')
hl.bind(MainMod .. " + F",                          hl.dsp.window.fullscreen())
hl.bind(MainMod .. " + P",			                hl.dsp.window.pseudo())
hl.bind(MainMod .. " + C",			                hl.dsp.window.close())
hl.bind(MainMod .. " + SPACE",		                hl.dsp.window.float({ action = "toggle" }) )
hl.bind(MainMod .. " + l",			                hl.dsp.focus({ direction = "right" }))
hl.bind(MainMod .. " + h",			                hl.dsp.focus({ direction = "left" }))
hl.bind(MainMod .. " + k",			                hl.dsp.focus({ direction = "up" }))
hl.bind(MainMod .. " + j",			                hl.dsp.focus({ direction = "down" }))
hl.bind(MainMod .. " + mouse:272",                  hl.dsp.window.drag(),   { mouse = true })
hl.bind(MainMod .. " + mouse:273",                  hl.dsp.window.resize(), { mouse = true })
hl.bind(MainMod .. " + S",                          hl.dsp.workspace.toggle_special("magic"))
hl.bind(MainMod .. " + SHIFT + S",                  hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(MainMod .. " +  TAB",                       hl.dsp.window.cycle_next({""}))
hl.bind(MainMod .. " + X", function ()
    if hl.get_workspace("special:minimized") then
        hl.dispatch(hl.dsp.window.move({ workspace = hl.get_active_workspace(), window = "tag:minimized" }))
        hl.dispatch(hl.dsp.window.clear_tags({ window = "tag:minimized" }))
    else
        hl.dispatch(hl.dsp.window.tag({ tag = "minimized", window = hl.get_active_window() }))
        hl.dispatch(hl.dsp.window.move({ workspace = "special:minimized", follow = false }))
    end
end)
hl.bind(Meh .. " + S",  hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(Meh .. " + C",	                hl.dsp.window.kill())
hl.bind(Meh .. " + l",			                        hl.dsp.window.swap({ direction = "right" }))
hl.bind(Meh .. " + h",			                        hl.dsp.window.swap({ direction = "left" }))
hl.bind(Meh .. " + k",			                        hl.dsp.window.swap({ direction = "up" }))
hl.bind(Meh .. " + j",			                        hl.dsp.window.swap({ direction = "down" }))

hl.bind(Hyper .. " + T",                     hl.dsp.exec_cmd("~/bin/alacritty.sh"))
hl.bind(Hyper .. " + E",			                hl.dsp.exec_cmd(FileManager))
hl.bind(Hyper .. " + B",			                hl.dsp.exec_cmd(Browser))
hl.bind(Hyper .. " + M",			                hl.dsp.exec_cmd("spotify-launcher"))
hl.bind(Hyper .. " + V",			                hl.dsp.exec_cmd("pavucontrol"))
hl.bind(Hyper .. " + E",			        hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(Hyper .. " + R",			                hl.dsp.exec_cmd(Menu))
hl.bind(Hyper .. " + F",                            hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/scripts/ranger.sh"))
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(MainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(MainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +10%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
