require('common')
hl.bind(Meh .. " + S",  hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(Meh .. " + C",	                hl.dsp.window.kill())
hl.bind(Meh .. " + l",			                        hl.dsp.window.swap({ direction = "right" }))
hl.bind(Meh .. " + h",			                        hl.dsp.window.swap({ direction = "left" }))
hl.bind(Meh .. " + k",			                        hl.dsp.window.swap({ direction = "up" }))
hl.bind(Meh .. " + j",			                        hl.dsp.window.swap({ direction = "down" }))

hl.bind(Hyper .. " + T",                     hl.dsp.exec_cmd("~/bin/alacritty.sh"))
hl.bind(Hyper .. " + E",			                hl.dsp.exec_cmd(FileManager))
hl.bind(Hyper .. " + B",			                hl.dsp.exec_cmd(Browser))
hl.bind(Hyper .. " + M",			                hl.dsp.exec_cmd("spotify-launcher"))
hl.bind(Hyper .. " + V",			                hl.dsp.exec_cmd("pavucontrol"))
hl.bind(Hyper .. " + E",			        hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(Hyper .. " + R",			                hl.dsp.exec_cmd(Menu))
hl.bind(Hyper .. " + F",                            hl.dsp.exec_cmd("~/bin/ranger.sh"))
